services:
  cache-server:
    image: chocolatefrappe/linux-package-cache-proxy:dev
    ports:
      - 80:80
    volumes:
      - type: volume
        source: cache
        target: /var/cache/linux-packages
volumes:
  cache:
