services:
  cacheserver:
    image: ghcr.io/cacheserver/linux-packages:main
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    stop_grace_period: 5m
    environment:
      - DOMAIN=localhost
      - PORT=80
    ports:
      - 8080:80
    volumes:
      - type: volume
        source: cache
        target: /var/cache/linux-packages
volumes:
  cache:
