services:
  cacheserver:
    image: ghcr.io/cacheserver/linux-packages:dev
    ports:
      - 80:80
    volumes:
      - type: volume
        source: cache
        target: /var/cache/linux-packages
    stop_grace_period: 5m
volumes:
  cache:
